[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["zomes/coordinator/*", "zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
holochain = "0.2.0"
hdk = "0.2.4"
hdi = "0.3.4"
serde = { version = "=1.0.163", default-features = false }
